# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a028d48a588061f249130dea078d486ac14356bda5d148ff621d0ec0481d8e7f6fd65b7ffaf9d03dd054ae6d42adbf9ce772ad02cf0394b155f1ff0af918a562

test:
  secret_key_base: 3c4a86d35d141a6be6bc32ca91b8d7dcff781249635bbd7ade081856783c58989406634168cc33fbce2798101ea81a5e0cc8f6f509807d4cb572680a767ae945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
